### ISSUE TITLE
Stopped working on Node v18

### ISSUE THREAD

**Issue by saulfloresbluetrail** [rickyes/jasypt#13]
Tried using it with node 18, and got the following error:

```
$ npx jasypt -p 0x1995 -e admin
node:internal/crypto/cipher:116
    this[kHandle].initiv(cipher, credential, iv, authTagLength);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:141:10)
    at Encryptor.encrypt (/home/code/node_modules/jasypt/encryptor.js:58:27)
    at Jasypt.encrypt (/home/code/node_modules/jasypt/jasypt.js:40:28)
    at encrypt (/home/code/node_modules/jasypt/bin/jasypt.js:16:22)
    at Command.<anonymous> (/home/code/node_modules/jasypt/node_modules/commander/index.js:412:13)
    at Command.emit (node:events:513:28)
    at Command.parseOptions (/home/code/node_modules/jasypt/node_modules/commander/index.js:730:14) {
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0
```

**Comment by rickyes** [comment]
Yes there is no Node.js V18 version yet, I will support it when I can, or PR is welcome!

**Comment by rappjt** [comment]
@rickyes - I am running into this issue as well, when upgrading to node v18 as v16 is close to ending LTS.  Any idea when a change to support v18 can be made?

**Comment by darkterra** [comment]
Hello there.

Try `NODE_OPTION=--openssl-legacy-provider`

I know this isn't a real fix, but it's a workaround until someone comes up with a PR or the author of this repository has time to update the code.
